#!/bin/bash
echo "Input file name (without numbers or extension):"
read imgname
echo "Input file extension:"
read imgext

ffmpeg -f image2 -r 30 -i $imgname%d.$imgext -vcodec libx264 -profile:v high444 -refs 16 -crf 0 -preset ultrafast $imgname.mp4

echo "Done! Goodbye!"
echo "_____________________________________"
echo 
